apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-x-static-web-app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx
